SELECT
    TICKER,
    PRIMARY_EXCHANGE_NAME,
    VARIABLE,
    VARIABLE_NAME,
    DATE,
    VALUE,
    'CYBERSYN.STOCK_PRICE_TIMESERIES' data_source_name
FROM {{source('FINANCIAL__ECONOMIC_ESSENTIALS', 'STOCK_PRICE_TIMESERIES')}} src
